import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ImagePlus, Save, Trash2, Users, Package, Settings2, ShieldCheck, ShieldOff } from 'lucide-react'
import { requireSupabase } from '../lib/supabase'
import type { Product, SiteSettings } from '../lib/types'

const emptyProduct: Product = { id:'', name:'', unit:'100g', price:0, description:'', image_url:'', active:true }
type Profile = { id:string; email:string|null; full_name:string|null; role:string }

export default function Admin({ products, setProducts, settings, reload }: {products:Product[]; setProducts:(p:Product[])=>void; settings:SiteSettings; reload:()=>Promise<void>}) {
 const sb=requireSupabase(); const nav=useNavigate(); const [role,setRole]=useState(''); const [form,setForm]=useState<Product>(emptyProduct); const [tab,setTab]=useState<'products'|'settings'|'users'>('products'); const [sform,setSform]=useState(settings); const [profiles,setProfiles]=useState<Profile[]>([]); const [userEmail,setUserEmail]=useState(''); const [newPassword,setNewPassword]=useState(''); const [userMsg,setUserMsg]=useState('');
 useEffect(()=>setSform(settings),[settings])
 const fn = () => import.meta.env.VITE_SUPABASE_FUNCTION_URL || `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/admin-user`
 const callFunction = async(body:any)=>{const session=(await sb.auth.getSession()).data.session;if(!session)throw new Error('Not logged in');const r=await fetch(fn(),{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
 const loadProfiles=async()=>{const {data}=await sb.from('profiles').select('id,email,full_name,role').order('created_at',{ascending:false});if(data)setProfiles(data as Profile[])}
 useEffect(()=>{(async()=>{const u=await sb.auth.getUser(); const {data}=await sb.from('profiles').select('role').eq('id',u.data.user?.id).single();if(!data||!['owner','admin'].includes(data.role)){nav('/admin-login');return}setRole(data.role);if(data.role==='owner')loadProfiles()})()},[nav,sb])
 const saveProduct=async()=>{const payload={name:form.name,unit:form.unit,price:Number(form.price),description:form.description||null,image_url:form.image_url||null,active:form.active};const {error}=form.id?await sb.from('products').update(payload).eq('id',form.id):await sb.from('products').insert(payload);if(error)alert(error.message);else{setForm(emptyProduct);await reload()}}
 const del=async(id:string)=>{if(!confirm('Delete product?'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error)alert(error.message);else await reload()}
 const saveSettings=async()=>{const {error}=await sb.from('site_settings').update({...sform}).eq('id',true);if(error)alert(error.message);else await reload()}
 const mediaUpload=async(e:React.ChangeEvent<HTMLInputElement>,kind:'hero'|'product')=>{const file=e.target.files?.[0];if(!file)return;const path=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await sb.storage.from('media').upload(path,file,{upsert:true});if(error){alert(error.message);return}const {data}=sb.storage.from('media').getPublicUrl(path);if(kind==='hero')setSform(v=>({...v,hero_image_url:data.publicUrl}));else setForm(v=>({...v,image_url:data.publicUrl}))}
 const managePassword=async()=>{setUserMsg('');try{const j=await callFunction({action:'upsert-user',email:userEmail,password:newPassword});setUserMsg(j.message)}catch(e){setUserMsg(e instanceof Error?e.message:'Failed')}}
 const changeRole=async(p:Profile,grant:boolean)=>{try{const j=await callFunction({action:grant?'grant-admin':'revoke-admin',userId:p.id});setUserMsg(j.message);await loadProfiles()}catch(e){setUserMsg(e instanceof Error?e.message:'Failed')}}
 return <main className="mx-auto max-w-7xl px-4 py-10 md:px-6"><div className="mb-6 flex flex-col gap-4 rounded-3xl bg-white p-5 shadow-xl md:flex-row md:items-center md:justify-between"><div><div className="text-sm font-bold uppercase tracking-[.2em] text-[#a75a42]">Private area</div><h1 className="text-3xl font-black text-[#7f1d1d]">Moshlai Admin</h1><div className="text-sm text-[#6a5149]">Role: {role}</div></div><button onClick={async()=>{await sb.auth.signOut();nav('/')}} className="btn-secondary">Logout</button></div>
 <div className="flex flex-wrap gap-2 rounded-2xl bg-white p-2 shadow"><button onClick={()=>setTab('products')} className={tab==='products'?'btn-primary':'btn-secondary'}><Package className="mr-2 inline" size={16}/>Products</button><button onClick={()=>setTab('settings')} className={tab==='settings'?'btn-primary':'btn-secondary'}><Settings2 className="mr-2 inline" size={16}/>Content</button>{role==='owner'&&<button onClick={()=>setTab('users')} className={tab==='users'?'btn-primary':'btn-secondary'}><Users className="mr-2 inline" size={16}/>Users</button>}</div>
 {tab==='products'&&<section className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.3fr]"><div className="glass rounded-3xl p-6"><h2 className="text-xl font-black text-[#7f1d1d]">{form.id?'Edit product':'Add product'}</h2><div className="mt-4 space-y-3"><input className="input" placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><div className="grid grid-cols-2 gap-3"><input className="input" placeholder="Unit e.g. 250g" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><input className="input" type="number" placeholder="Price" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></div><textarea className="input min-h-28" placeholder="Description" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/><input className="input" placeholder="Image URL" value={form.image_url||''} onChange={e=>setForm({...form,image_url:e.target.value})}/><label className="flex cursor-pointer items-center gap-2 rounded-xl bg-[#f3e8df] p-3 font-bold"><ImagePlus size={18}/>Upload image<input hidden type="file" accept="image/*" onChange={e=>mediaUpload(e,'product')}/></label><button className="btn-primary w-full" onClick={saveProduct}><Save className="mr-2 inline" size={17}/>{form.id?'Update':'Save'} product</button>{form.id&&<button onClick={()=>setForm(emptyProduct)} className="btn-secondary w-full">Cancel</button>}</div></div><div className="glass rounded-3xl p-6"><h2 className="text-xl font-black text-[#7f1d1d]">Products</h2><div className="mt-4 space-y-3">{products.map(p=><div key={p.id} className="flex items-center gap-3 rounded-2xl bg-white p-3"><img src={p.image_url||'/moshlai-chilli-demo.png'} className="h-16 w-16 rounded-xl object-cover"/><div className="flex-1"><div className="font-bold">{p.name}</div><div className="text-sm text-[#6a5149]">{p.unit} • ৳{Number(p.price).toFixed(0)}</div></div><button className="btn-secondary" onClick={()=>setForm(p)}>Edit</button><button className="rounded-xl bg-red-50 p-3 text-red-700" onClick={()=>del(p.id)}><Trash2 size={17}/></button></div>)}</div></div></section>}
 {tab==='settings'&&<section className="mt-6"><div className="glass rounded-3xl p-6 md:p-8"><h2 className="text-xl font-black text-[#7f1d1d]">Website content</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><input className="input" value={sform.hero_title} onChange={e=>setSform({...sform,hero_title:e.target.value})} placeholder="Hero title"/><input className="input" value={sform.hero_subtitle} onChange={e=>setSform({...sform,hero_subtitle:e.target.value})} placeholder="Hero subtitle"/><input className="input" value={sform.about_title} onChange={e=>setSform({...sform,about_title:e.target.value})} placeholder="About title"/><input className="input" value={sform.contact_phone} onChange={e=>setSform({...sform,contact_phone:e.target.value})} placeholder="Phone"/><input className="input" value={sform.contact_whatsapp} onChange={e=>setSform({...sform,contact_whatsapp:e.target.value})} placeholder="WhatsApp number"/><input className="input" value={sform.contact_address} onChange={e=>setSform({...sform,contact_address:e.target.value})} placeholder="Address"/><input className="input" value={sform.facebook_url||''} onChange={e=>setSform({...sform,facebook_url:e.target.value})} placeholder="Facebook URL"/><input className="input" value={sform.instagram_url||''} onChange={e=>setSform({...sform,instagram_url:e.target.value})} placeholder="Instagram URL"/><textarea className="input min-h-36 md:col-span-2" value={sform.about_text} onChange={e=>setSform({...sform,about_text:e.target.value})} placeholder="About text"/><input className="input md:col-span-2" value={sform.hero_image_url||''} onChange={e=>setSform({...sform,hero_image_url:e.target.value})} placeholder="Hero image URL"/><label className="flex cursor-pointer items-center gap-2 rounded-xl bg-[#f3e8df] p-3 font-bold md:col-span-2"><ImagePlus size={18}/>Upload hero image<input hidden type="file" accept="image/*" onChange={e=>mediaUpload(e,'hero')}/></label></div><button onClick={saveSettings} className="btn-primary mt-5"><Save className="mr-2 inline" size={17}/>Save content</button></div></section>}
 {tab==='users'&&role==='owner'&&<section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="glass rounded-3xl p-6"><h2 className="text-xl font-black text-[#7f1d1d]">Password management</h2><p className="mt-2 text-sm text-[#6a5149]">Create a new user or set/reset an existing user's password.</p><div className="mt-5 space-y-3"><input className="input" type="email" placeholder="User email" value={userEmail} onChange={e=>setUserEmail(e.target.value)}/><input className="input" type="password" placeholder="New password (6+ chars)" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><button onClick={managePassword} className="btn-primary w-full">Set / reset password</button>{userMsg&&<div className="rounded-xl bg-[#f5e7db] p-3 text-sm">{userMsg}</div>}</div></div><div className="glass rounded-3xl p-6"><h2 className="text-xl font-black text-[#7f1d1d]">Users & one extra admin</h2><p className="mt-2 text-sm text-[#6a5149]">You are the owner. Only one other account can have admin access at a time.</p><div className="mt-4 space-y-3">{profiles.map(p=><div key={p.id} className="rounded-2xl bg-white p-4"><div className="flex items-start gap-3"><div className="flex-1"><div className="font-bold">{p.full_name||'Unnamed user'}</div><div className="text-sm text-[#6a5149]">{p.email||'No email'} • {p.role}</div></div>{p.role==='admin'?<button className="btn-secondary" onClick={()=>changeRole(p,false)}><ShieldOff className="mr-1 inline" size={16}/>Revoke</button>:p.role==='user'?<button className="btn-primary" onClick={()=>changeRole(p,true)}><ShieldCheck className="mr-1 inline" size={16}/>Make admin</button>:<span className="rounded-xl bg-[#f3e8df] px-3 py-2 text-sm font-bold">Owner</span>}</div></div>)}</div></div></section>}
 </main>
}
