import { useState } from 'react'
import { Link, useNavigate, useLocation } from 'react-router-dom'
import { supabase } from '../lib/supabase'

export default function Auth({ mode }: { mode: 'login'|'signup' }) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [msg,setMsg]=useState(''); const nav=useNavigate(); const loc=useLocation()
  const submit=async(e:React.FormEvent)=>{e.preventDefault(); setMsg(''); if(!supabase){setMsg('Supabase config missing.');return} const res=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{full_name:name}}}); if(res.error){setMsg(res.error.message);return} setMsg(mode==='signup'?'Account created. Check your email if email confirmation is enabled.':'Logged in.'); if(mode==='login') nav((loc.state as any)?.from || '/')}
  return <main className="mx-auto max-w-md px-4 py-16"><div className="glass rounded-3xl p-7 md:p-9"><h1 className="text-3xl font-black text-[#7f1d1d]">{mode==='login'?'Login':'Create account'}</h1><form className="mt-6 space-y-4" onSubmit={submit}>{mode==='signup'&&<input className="input" placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/>}<input className="input" type="email" required placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input" type="password" required minLength={6} placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn-primary w-full">{mode==='login'?'Login':'Sign up'}</button></form>{msg&&<p className="mt-4 rounded-xl bg-[#f5e7db] p-3 text-sm">{msg}</p>}<p className="mt-5 text-sm text-[#6a5149]">{mode==='login'?<>New here? <Link className="font-bold text-[#7f1d1d]" to="/signup">Create account</Link></>:<>Already have an account? <Link className="font-bold text-[#7f1d1d]" to="/login">Login</Link></>}</p></div></main>
}
